package pl.poczta_polska.e_nadawca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-07-27T18:28:01.130+02:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://e-nadawca.poczta-polska.pl", name = "ElektronicznyNadawca")
@XmlSeeAlso({ObjectFactory.class})
public interface ElektronicznyNadawca {

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getFirmowaPocztaBook")
    @RequestWrapper(localName = "getFirmowaPocztaBook", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetFirmowaPocztaBook")
    @ResponseWrapper(localName = "getFirmowaPocztaBookResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetFirmowaPocztaBookResponse")
    public void getFirmowaPocztaBook(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateEnvelopeBufor")
    @RequestWrapper(localName = "updateEnvelopeBufor", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateEnvelopeBufor")
    @ResponseWrapper(localName = "updateEnvelopeBuforResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateEnvelopeBuforResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> updateEnvelopeBufor(

        @WebParam(name = "bufor", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.BuforType> bufor
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddresLabelCompact")
    @RequestWrapper(localName = "getAddresLabelCompact", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddresLabelCompact")
    @ResponseWrapper(localName = "getAddresLabelCompactResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddresLabelCompactResponse")
    public void getAddresLabelCompact(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/changePassword")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ChangePasswordResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> changePassword(

        @WebParam(name = "newPassword", targetNamespace = "")
        java.lang.String newPassword
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeStatus")
    @RequestWrapper(localName = "getEnvelopeStatus", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeStatus")
    @ResponseWrapper(localName = "getEnvelopeStatusResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeStatusResponse")
    public void getEnvelopeStatus(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeStatus", targetNamespace = "")
        javax.xml.ws.Holder<EnvelopeStatusType> envelopeStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/isObszarMiasto")
    @RequestWrapper(localName = "isObszarMiasto", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.IsObszarMiasto")
    @ResponseWrapper(localName = "isObszarMiastoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.IsObszarMiastoResponse")
    @WebResult(name = "obszarAdresowy", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ObszarAdresowyResponseType> isObszarMiasto(

        @WebParam(name = "adres", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.ObszarAdresowyType> adres
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getBlankietPobraniaByGuids")
    @RequestWrapper(localName = "getBlankietPobraniaByGuids", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetBlankietPobraniaByGuids")
    @ResponseWrapper(localName = "getBlankietPobraniaByGuidsResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetBlankietPobraniaByGuidsResponse")
    public void getBlankietPobraniaByGuids(

        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.AddressLabelContent>> content,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getZapowiedziFaktur")
    @RequestWrapper(localName = "getZapowiedziFaktur", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetZapowiedziFaktur")
    @ResponseWrapper(localName = "getZapowiedziFakturResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetZapowiedziFakturResponse")
    @WebResult(name = "zapowiedzFakturyZipFile", targetNamespace = "")
    public java.util.List<byte[]> getZapowiedziFaktur(

        @WebParam(name = "data", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar data
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/downloadIWDContent")
    @RequestWrapper(localName = "downloadIWDContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.DownloadIWDContent")
    @ResponseWrapper(localName = "downloadIWDContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.DownloadIWDContentResponse")
    public void downloadIWDContent(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "IWDContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> iwdContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addShipment")
    @RequestWrapper(localName = "addShipment", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddShipment")
    @ResponseWrapper(localName = "addShipmentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddShipmentResponse")
    @WebResult(name = "retval", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.AddShipmentResponseItemType> addShipment(

        @WebParam(name = "przesylki", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.PrzesylkaType> przesylki,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/cancelReklamacja")
    @RequestWrapper(localName = "cancelReklamacja", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CancelReklamacja")
    @ResponseWrapper(localName = "cancelReklamacjaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CancelReklamacjaResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> cancelReklamacja(

        @WebParam(name = "idRelkamacja", targetNamespace = "")
        int idRelkamacja
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/deleteShopEZwroty")
    @RequestWrapper(localName = "deleteShopEZwroty", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.DeleteShopEZwroty")
    @ResponseWrapper(localName = "deleteShopEZwrotyResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.DeleteShopEZwrotyResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> deleteShopEZwroty(

        @WebParam(name = "idShop", targetNamespace = "")
        int idShop
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/sendEnvelope")
    @RequestWrapper(localName = "sendEnvelope", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SendEnvelope")
    @ResponseWrapper(localName = "sendEnvelopeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SendEnvelopeResponseType")
    public void sendEnvelope(

        @WebParam(name = "urzadNadania", targetNamespace = "")
        java.lang.Integer urzadNadania,
        @WebParam(name = "pakiet", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.PakietType> pakiet,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(name = "profil", targetNamespace = "")
        pl.poczta_polska.e_nadawca.ProfilType profil,
        @WebParam(mode = WebParam.Mode.OUT, name = "idEnvelope", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeStatus", targetNamespace = "")
        javax.xml.ws.Holder<EnvelopeStatusType> envelopeStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeFilename", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> envelopeFilename
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getJednostkaOrganizacyjna")
    @RequestWrapper(localName = "getJednostkaOrganizacyjna", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetJednostkaOrganizacyjna")
    @ResponseWrapper(localName = "getJednostkaOrganizacyjnaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetJednostkaOrganizacyjnaResponse")
    public void getJednostkaOrganizacyjna(

        @WebParam(name = "jednostka", targetNamespace = "")
        pl.poczta_polska.e_nadawca.JednostkaOrganizacyjnaType jednostka,
        @WebParam(mode = WebParam.Mode.OUT, name = "jednostkaOrganizacyjna", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.JednostkaOrganizacyjnaType>> jednostkaOrganizacyjna,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeList")
    @RequestWrapper(localName = "getEnvelopeList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeList")
    @ResponseWrapper(localName = "getEnvelopeListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeListResponse")
    @WebResult(name = "envelopes", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.EnvelopeInfoType> getEnvelopeList(

        @WebParam(name = "startDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar endDate
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddressLabel")
    @RequestWrapper(localName = "getAddressLabel", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddressLabel")
    @ResponseWrapper(localName = "getAddressLabelResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddressLabelResponse")
    public void getAddressLabel(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.AddressLabelContent>> content,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getKierunkiInfo")
    @RequestWrapper(localName = "getKierunkiInfo", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetKierunkiInfo")
    @ResponseWrapper(localName = "getKierunkiInfoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetKierunkiInfoResponse")
    public void getKierunkiInfo(

        @WebParam(name = "plan", targetNamespace = "")
        java.lang.String plan,
        @WebParam(mode = WebParam.Mode.OUT, name = "lastUpdate", targetNamespace = "")
        javax.xml.ws.Holder<javax.xml.datatype.XMLGregorianCalendar> lastUpdate,
        @WebParam(mode = WebParam.Mode.OUT, name = "usluga", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.UslugiType>> usluga,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAccountList")
    @RequestWrapper(localName = "getAccountList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAccountList")
    @ResponseWrapper(localName = "getAccountListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAccountListResponse")
    @WebResult(name = "account", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.AccountType> getAccountList()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeBufor")
    @RequestWrapper(localName = "getEnvelopeBufor", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeBufor")
    @ResponseWrapper(localName = "getEnvelopeBuforResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeBuforResponse")
    public void getEnvelopeBufor(

        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "przesylka", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.PrzesylkaType>> przesylka,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeContentFull")
    @RequestWrapper(localName = "getEnvelopeContentFull", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeContentFull")
    @ResponseWrapper(localName = "getEnvelopeContentFullResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeContentFullResponse")
    @WebResult(name = "przesylka", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.PrzesylkaFullType> getEnvelopeContentFull(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/wyslijLinkaOStatusieEZwrotu")
    @RequestWrapper(localName = "wyslijLinkaOStatusieEZwrotu", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.WyslijLinkaOStatusieEZwrotu")
    @ResponseWrapper(localName = "wyslijLinkaOStatusieEZwrotuResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.WyslijLinkaOStatusieEZwrotuResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> wyslijLinkaOStatusieEZwrotu(

        @WebParam(name = "guidZgodaEZwrot", targetNamespace = "")
        java.util.List<java.lang.String> guidZgodaEZwrot
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addRozbieznoscDoZapowiedziFaktur")
    @RequestWrapper(localName = "addRozbieznoscDoZapowiedziFaktur", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddRozbieznoscDoZapowiedziFaktur")
    @ResponseWrapper(localName = "addRozbieznoscDoZapowiedziFakturResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddRozbieznoscDoZapowiedziFakturResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> addRozbieznoscDoZapowiedziFaktur(

        @WebParam(name = "rozbieznosciZipFile", targetNamespace = "")
        java.util.List<byte[]> rozbieznosciZipFile
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/zamowKuriera")
    @RequestWrapper(localName = "zamowKuriera", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ZamowKuriera")
    @ResponseWrapper(localName = "zamowKurieraResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ZamowKurieraResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> zamowKuriera(

        @WebParam(name = "miejsceOdbioru", targetNamespace = "")
        pl.poczta_polska.e_nadawca.AdresType miejsceOdbioru,
        @WebParam(name = "nadawca", targetNamespace = "")
        pl.poczta_polska.e_nadawca.AdresType nadawca,
        @WebParam(name = "oczekiwanaDataOdbioru", targetNamespace = "")
        java.lang.String oczekiwanaDataOdbioru,
        @WebParam(name = "oczekiwanaGodzinaOdbioru", targetNamespace = "")
        java.lang.String oczekiwanaGodzinaOdbioru,
        @WebParam(name = "szacowanaIloscPrzeslek", targetNamespace = "")
        java.lang.String szacowanaIloscPrzeslek,
        @WebParam(name = "szacowanaLacznaMasaPrzesylek", targetNamespace = "")
        java.lang.String szacowanaLacznaMasaPrzesylek
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getUrzedyNadania")
    @RequestWrapper(localName = "getUrzedyNadania", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetUrzedyNadania")
    @ResponseWrapper(localName = "getUrzedyNadaniaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetUrzedyNadaniaResponse")
    @WebResult(name = "urzedyNadania", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.UrzadNadaniaFullType> getUrzedyNadania()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getUrzedyWydajaceEPrzesylki")
    @RequestWrapper(localName = "getUrzedyWydajaceEPrzesylki", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetUrzedyWydajaceEPrzesylki")
    @ResponseWrapper(localName = "getUrzedyWydajaceEPrzesylkiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetUrzedyWydajaceEPrzesylkiResponse")
    @WebResult(name = "urzadWydaniaEPrzesylki", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.UrzadWydaniaEPrzesylkiType> getUrzedyWydajaceEPrzesylki()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeContentShort")
    @RequestWrapper(localName = "getEnvelopeContentShort", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeContentShort")
    @ResponseWrapper(localName = "getEnvelopeContentShortResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeContentShortResponse")
    @WebResult(name = "przesylka", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.PrzesylkaShortType> getEnvelopeContentShort(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/clearEnvelope")
    @RequestWrapper(localName = "clearEnvelope", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ClearEnvelope")
    @ResponseWrapper(localName = "clearEnvelopeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ClearEnvelopeResponse")
    public void clearEnvelope(

        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "retval", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> retval,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateProfil")
    @RequestWrapper(localName = "updateProfil", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateProfil")
    @ResponseWrapper(localName = "updateProfilResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateProfilResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> updateProfil(

        @WebParam(name = "profil", targetNamespace = "")
        pl.poczta_polska.e_nadawca.ProfilType profil
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setStatusZgodyNaEZwrot")
    @RequestWrapper(localName = "setStatusZgodyNaEZwrot", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetStatusZgodyNaEZwrot")
    @ResponseWrapper(localName = "setStatusZgodyNaEZwrotResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetStatusZgodyNaEZwrotResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> setStatusZgodyNaEZwrot(

        @WebParam(name = "statusZgody", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.StatusZgodyEZwrotType> statusZgody
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/moveShipments")
    @RequestWrapper(localName = "moveShipments", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.MoveShipments")
    @ResponseWrapper(localName = "moveShipmentsResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.MoveShipmentsResponse")
    public void moveShipments(

        @WebParam(name = "idBuforFrom", targetNamespace = "")
        int idBuforFrom,
        @WebParam(name = "idBuforTo", targetNamespace = "")
        int idBuforTo,
        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(mode = WebParam.Mode.OUT, name = "notMovedGuid", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<java.lang.String>> notMovedGuid,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEnvelopeBuforList")
    @RequestWrapper(localName = "getEnvelopeBuforList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeBuforList")
    @ResponseWrapper(localName = "getEnvelopeBuforListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEnvelopeBuforListResponse")
    public void getEnvelopeBuforList(

        @WebParam(mode = WebParam.Mode.OUT, name = "bufor", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.BuforType>> bufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getListaPowodowReklamacji")
    @RequestWrapper(localName = "getListaPowodowReklamacji", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetListaPowodowReklamacji")
    @ResponseWrapper(localName = "getListaPowodowReklamacjiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetListaPowodowReklamacjiResponse")
    @WebResult(name = "kategoriePowodowReklamacji", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.KategoriePowodowReklamacjiType> getListaPowodowReklamacji()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createShopEZwroty")
    @RequestWrapper(localName = "createShopEZwroty", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateShopEZwroty")
    @ResponseWrapper(localName = "createShopEZwrotyResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateShopEZwrotyResponse")
    public void createShopEZwroty(

        @WebParam(name = "shop", targetNamespace = "")
        pl.poczta_polska.e_nadawca.ShopEZwrotyType shop,
        @WebParam(mode = WebParam.Mode.OUT, name = "idShop", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idShop,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addZalacznikDoReklamacji")
    @RequestWrapper(localName = "addZalacznikDoReklamacji", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddZalacznikDoReklamacji")
    @ResponseWrapper(localName = "addZalacznikDoReklamacjiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddZalacznikDoReklamacjiResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> addZalacznikDoReklamacji(

        @WebParam(name = "idReklamacja", targetNamespace = "")
        java.lang.String idReklamacja,
        @WebParam(name = "zalacznik", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.ZalacznikDoReklamacjiType> zalacznik
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createAccount")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateAccountResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> createAccount(

        @WebParam(name = "account", targetNamespace = "")
        pl.poczta_polska.e_nadawca.AccountType account
    );

    /**
     * The method returns parcels printouts  for passed guid's
     */
    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getPrintForParcel")
    @RequestWrapper(localName = "getPrintForParcel", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPrintForParcel")
    @ResponseWrapper(localName = "getPrintForParcelResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPrintForParcelResponse")
    public void getPrintForParcel(

        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "type", targetNamespace = "")
        pl.poczta_polska.e_nadawca.PrintType type,
        @WebParam(mode = WebParam.Mode.OUT, name = "printResult", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.PrintResultType>> printResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEZDO")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEZDOResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", partName = "parameters")
    public GetEZDOResponse getEZDO(

        @WebParam(partName = "parameters", name = "getEZDO", targetNamespace = "http://e-nadawca.poczta-polska.pl")
        GetEZDO parameters
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddresLabelByGuidCompact")
    @RequestWrapper(localName = "getAddresLabelByGuidCompact", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddresLabelByGuidCompact")
    @ResponseWrapper(localName = "getAddresLabelByGuidCompactResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddresLabelByGuidCompactResponse")
    public void getAddresLabelByGuidCompact(

        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getPlacowkiPocztowe")
    @RequestWrapper(localName = "getPlacowkiPocztowe", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPlacowkiPocztowe")
    @ResponseWrapper(localName = "getPlacowkiPocztoweResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPlacowkiPocztoweResponse")
    @WebResult(name = "placowka", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.PlacowkaPocztowaType> getPlacowkiPocztowe(

        @WebParam(name = "idWojewodztwo", targetNamespace = "")
        java.lang.String idWojewodztwo
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getListaZgodEZwrotow")
    @RequestWrapper(localName = "getListaZgodEZwrotow", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetListaZgodEZwrotow")
    @ResponseWrapper(localName = "getListaZgodEZwrotowResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetListaZgodEZwrotowResponse")
    public void getListaZgodEZwrotow(

        @WebParam(name = "status", targetNamespace = "")
        pl.poczta_polska.e_nadawca.StatusZgodyEZwrotNameType status,
        @WebParam(mode = WebParam.Mode.OUT, name = "lista", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.OczekujeNaZgodeEZwrotType>> lista,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getAddresLabelByGuid")
    @RequestWrapper(localName = "getAddresLabelByGuid", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddresLabelByGuid")
    @ResponseWrapper(localName = "getAddresLabelByGuidResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetAddresLabelByGuidResponse")
    public void getAddresLabelByGuid(

        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "content", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.AddressLabelContent>> content,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/clearEnvelopeByGuids")
    @RequestWrapper(localName = "clearEnvelopeByGuids", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ClearEnvelopeByGuids")
    @ResponseWrapper(localName = "clearEnvelopeByGuidsResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.ClearEnvelopeByGuidsResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> clearEnvelopeByGuids(

        @WebParam(name = "guid", targetNamespace = "")
        java.util.List<java.lang.String> guid,
        @WebParam(name = "idBufor", targetNamespace = "")
        java.lang.Integer idBufor
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/uploadIWDContent")
    @RequestWrapper(localName = "uploadIWDContent", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UploadIWDContent")
    @ResponseWrapper(localName = "uploadIWDContentResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SendEnvelopeResponseType")
    public void uploadIWDContent(

        @WebParam(name = "urzadNadania", targetNamespace = "")
        java.lang.Integer urzadNadania,
        @WebParam(name = "IWDContent", targetNamespace = "")
        byte[] iwdContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "idEnvelope", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idEnvelope,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeStatus", targetNamespace = "")
        javax.xml.ws.Holder<EnvelopeStatusType> envelopeStatus,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "envelopeFilename", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> envelopeFilename
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/hello")
    @RequestWrapper(localName = "hello", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.HelloResponse")
    @WebResult(name = "out", targetNamespace = "")
    public java.lang.String hello(

        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getPasswordExpiredDate")
    @RequestWrapper(localName = "getPasswordExpiredDate", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPasswordExpiredDate")
    @ResponseWrapper(localName = "getPasswordExpiredDateResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPasswordExpiredDateResponse")
    @WebResult(name = "dataWygasniecia", targetNamespace = "")
    public javax.xml.datatype.XMLGregorianCalendar getPasswordExpiredDate()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setEnvelopeBuforDataNadania")
    @RequestWrapper(localName = "setEnvelopeBuforDataNadania", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetEnvelopeBuforDataNadania")
    @ResponseWrapper(localName = "setEnvelopeBuforDataNadaniaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetEnvelopeBuforDataNadaniaResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> setEnvelopeBuforDataNadania(

        @WebParam(name = "dataNadania", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataNadania
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEZDOList")
    @RequestWrapper(localName = "getEZDOList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEZDOList")
    @ResponseWrapper(localName = "getEZDOListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetEZDOListResponse")
    @WebResult(name = "EZDOPakiet", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.EZDOPakietType> getEZDOList()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getWplatyCKP")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getWplatyCKPResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", partName = "parameters")
    public GetWplatyCKPResponse getWplatyCKP(

        @WebParam(partName = "parameters", name = "getWplatyCKP", targetNamespace = "http://e-nadawca.poczta-polska.pl")
        GetWplatyCKP parameters
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addOdwolanieDoReklamacji")
    @RequestWrapper(localName = "addOdwolanieDoReklamacji", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddOdwolanieDoReklamacji")
    @ResponseWrapper(localName = "addOdwolanieDoReklamacjiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddOdwolanieDoReklamacjiResponse")
    public void addOdwolanieDoReklamacji(

        @WebParam(name = "reklamacja", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.ReklamowanaPrzesylkaType> reklamacja,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "reklamacjaInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ReklamacjaInfoType>> reklamacjaInfo
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getReklamacje")
    @RequestWrapper(localName = "getReklamacje", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetReklamacje")
    @ResponseWrapper(localName = "getReklamacjeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetReklamacjeResponse")
    @WebResult(name = "reklamacja", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ReklamacjaRozpatrzonaType> getReklamacje(

        @WebParam(name = "dataRozpatrzenia", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar dataRozpatrzenia
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getEPOStatus")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getEPOStatusResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", partName = "parameters")
    public GetEPOStatusResponse getEPOStatus(

        @WebParam(partName = "parameters", name = "getEPOStatus", targetNamespace = "http://e-nadawca.poczta-polska.pl")
        GetEPOStatus parameters
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/isMiejscowa")
    @RequestWrapper(localName = "isMiejscowa", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.IsMiejscowa")
    @ResponseWrapper(localName = "isMiejscowaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.IsMiejscowaResponse")
    @WebResult(name = "trasaResponse", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.TrasaResponseType> isMiejscowa(

        @WebParam(name = "trasaRequest", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.TrasaRequestType> trasaRequest
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getProfilList")
    @RequestWrapper(localName = "getProfilList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetProfilList")
    @ResponseWrapper(localName = "getProfilListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetProfilListResponse")
    @WebResult(name = "profil", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ProfilType> getProfilList()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateAccount")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateAccount")
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateAccountResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> updateAccount(

        @WebParam(name = "account", targetNamespace = "")
        pl.poczta_polska.e_nadawca.AccountType account
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createEnvelopeBufor")
    @RequestWrapper(localName = "createEnvelopeBufor", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateEnvelopeBufor")
    @ResponseWrapper(localName = "createEnvelopeBuforResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateEnvelopeBuforResponse")
    public void createEnvelopeBufor(

        @WebParam(name = "bufor", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.BuforType> bufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "createdBufor", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.BuforType>> createdBufor,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getGuid")
    @RequestWrapper(localName = "getGuid", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetGuid")
    @ResponseWrapper(localName = "getGuidResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetGuidResponse")
    @WebResult(name = "guid", targetNamespace = "")
    public java.util.List<java.lang.String> getGuid(

        @WebParam(name = "ilosc", targetNamespace = "")
        int ilosc
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/addReklamacje")
    @RequestWrapper(localName = "addReklamacje", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddReklamacje")
    @ResponseWrapper(localName = "addReklamacjeResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.AddReklamacjeResponse")
    public void addReklamacje(

        @WebParam(name = "reklamowanaPrzesylka", targetNamespace = "")
        java.util.List<pl.poczta_polska.e_nadawca.ReklamowanaPrzesylkaType> reklamowanaPrzesylka,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error,
        @WebParam(mode = WebParam.Mode.OUT, name = "reklamacjaInfo", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ReklamacjaInfoType>> reklamacjaInfo
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setJednostkaOrganizacyjna")
    @RequestWrapper(localName = "setJednostkaOrganizacyjna", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetJednostkaOrganizacyjna")
    @ResponseWrapper(localName = "setJednostkaOrganizacyjnaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetJednostkaOrganizacyjnaResponse")
    public void setJednostkaOrganizacyjna(

        @WebParam(mode = WebParam.Mode.INOUT, name = "jednostkaOrganizacyjna", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.JednostkaOrganizacyjnaType>> jednostkaOrganizacyjna,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getKarty")
    @RequestWrapper(localName = "getKarty", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetKarty")
    @ResponseWrapper(localName = "getKartyResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetKartyResponse")
    public void getKarty(

        @WebParam(name = "idKarta", targetNamespace = "")
        java.util.List<java.lang.Integer> idKarta,
        @WebParam(mode = WebParam.Mode.OUT, name = "karta", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.KartaType>> karta,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getKierunki")
    @RequestWrapper(localName = "getKierunki", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetKierunki")
    @ResponseWrapper(localName = "getKierunkiResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetKierunkiResponse")
    public void getKierunki(

        @WebParam(name = "plan", targetNamespace = "")
        java.lang.String plan,
        @WebParam(name = "prefixKodPocztowy", targetNamespace = "")
        java.lang.String prefixKodPocztowy,
        @WebParam(mode = WebParam.Mode.OUT, name = "kierunek", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.KierunekType>> kierunek,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getShopEZwrotyList")
    @RequestWrapper(localName = "getShopEZwrotyList", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetShopEZwrotyList")
    @ResponseWrapper(localName = "getShopEZwrotyListResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetShopEZwrotyListResponse")
    @WebResult(name = "shops", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ShopEZwrotyInfoType> getShopEZwrotyList()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/setAktywnaKarta")
    @RequestWrapper(localName = "setAktywnaKarta", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetAktywnaKarta")
    @ResponseWrapper(localName = "setAktywnaKartaResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.SetAktywnaKartaResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> setAktywnaKarta(

        @WebParam(name = "idKarta", targetNamespace = "")
        int idKarta
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/updateShopEZwroty")
    @RequestWrapper(localName = "updateShopEZwroty", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateShopEZwroty")
    @ResponseWrapper(localName = "updateShopEZwrotyResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.UpdateShopEZwrotyResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> updateShopEZwroty(

        @WebParam(name = "shop", targetNamespace = "")
        pl.poczta_polska.e_nadawca.ShopEZwrotyType shop
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getOutboxBook")
    @RequestWrapper(localName = "getOutboxBook", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetOutboxBook")
    @ResponseWrapper(localName = "getOutboxBookResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetOutboxBookResponse")
    public void getOutboxBook(

        @WebParam(name = "idEnvelope", targetNamespace = "")
        int idEnvelope,
        @WebParam(name = "includeNierejestrowane", targetNamespace = "")
        java.lang.Boolean includeNierejestrowane,
        @WebParam(mode = WebParam.Mode.OUT, name = "pdfContent", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> pdfContent,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getUbezpieczeniaInfo")
    @RequestWrapper(localName = "getUbezpieczeniaInfo", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetUbezpieczeniaInfo")
    @ResponseWrapper(localName = "getUbezpieczeniaInfoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetUbezpieczeniaInfoResponse")
    @WebResult(name = "poziomyUbezpieczenia", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.UbezpieczeniaInfoType> getUbezpieczeniaInfo()
;

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/createProfil")
    @RequestWrapper(localName = "createProfil", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateProfil")
    @ResponseWrapper(localName = "createProfilResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.CreateProfilResponse")
    @WebResult(name = "error", targetNamespace = "")
    public java.util.List<pl.poczta_polska.e_nadawca.ErrorType> createProfil(

        @WebParam(name = "profil", targetNamespace = "")
        pl.poczta_polska.e_nadawca.ProfilType profil
    );

    @WebMethod(action = "http://e-nadawca.poczta-polska.pl/getPaczkaKorzysciInfo")
    @RequestWrapper(localName = "getPaczkaKorzysciInfo", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPaczkaKorzysciInfo")
    @ResponseWrapper(localName = "getPaczkaKorzysciInfoResponse", targetNamespace = "http://e-nadawca.poczta-polska.pl", className = "pl.poczta_polska.e_nadawca.GetPaczkaKorzysciInfoResponse")
    public void getPaczkaKorzysciInfo(

        @WebParam(mode = WebParam.Mode.OUT, name = "status", targetNamespace = "")
        javax.xml.ws.Holder<StatusPaczkaKorzysciType> status,
        @WebParam(mode = WebParam.Mode.OUT, name = "idKarta", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> idKarta,
        @WebParam(mode = WebParam.Mode.OUT, name = "info", targetNamespace = "")
        javax.xml.ws.Holder<InfoPaczkaKorzysciType> info,
        @WebParam(mode = WebParam.Mode.OUT, name = "error", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<pl.poczta_polska.e_nadawca.ErrorType>> error
    );
}
