package pl.poczta_polska.e_nadawca;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-23T18:25:48.351+01:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "ElektronicznyNadawca",
                  wsdlLocation = "file:/C:/DEV/order-manager-parent/enadawca-client/src/main/resources/en.wsdl",
                  targetNamespace = "http://e-nadawca.poczta-polska.pl")
public class ElektronicznyNadawca_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://e-nadawca.poczta-polska.pl", "ElektronicznyNadawca");
    public final static QName ENSoap = new QName("http://e-nadawca.poczta-polska.pl", "ENSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/DEV/order-manager-parent/enadawca-client/src/main/resources/en.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ElektronicznyNadawca_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/DEV/order-manager-parent/enadawca-client/src/main/resources/en.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ElektronicznyNadawca_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ElektronicznyNadawca_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ElektronicznyNadawca_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ElektronicznyNadawca_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ElektronicznyNadawca_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ElektronicznyNadawca_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ElektronicznyNadawca
     */
    @WebEndpoint(name = "ENSoap")
    public ElektronicznyNadawca getENSoap() {
        return super.getPort(ENSoap, ElektronicznyNadawca.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ElektronicznyNadawca
     */
    @WebEndpoint(name = "ENSoap")
    public ElektronicznyNadawca getENSoap(WebServiceFeature... features) {
        return super.getPort(ENSoap, ElektronicznyNadawca.class, features);
    }

}
